### ISSUE TITLE
ARM support

### ISSUE THREAD

**Issue by nmcc1212** [caseyscarborough/qbittorrent-exporter#12]
Any possibility of ARM support for raspberry pi's and other ARM based devices

**Comment by caseyscarborough** [comment]
Hi @nmcc1212, that's a great point and I hadn't considered that. This is the first time I've worked with Docker images for ARM, but I just pushed a `linux/arm64` version to DockerHub for `caseyscarborough/qbittorrent-exporter:latest`. I believe it will only work with 64-bit ARM processors though. Will that work for you?

**Comment by caseyscarborough** [comment]
If other architectures are needed I can work those in as well, but the base image this project uses currently only supports `linux/amd64` and `linux/arm64`, so it will take a little more work.

**Comment by nmcc1212** [comment]
raspberry pi's are arm64, so if you could add support for that is would be much appreciated

**Comment by nmcc1212** [comment]
It works on my pi4! thanks
