### ISSUE TITLE
Number Format Exception

### ISSUE THREAD

**Issue by nmcc1212** [caseyscarborough/qbittorrent-exporter#13]
All was working fine until it seemed to randomly stop working, even after restarting docker container get the same error 
`An error occurred. java.lang.NumberFormatException: Expected a long but was 2.5 at line 1 column 2000 path $.max_ratio`

docker container logs show 
```
com.google.gson.JsonSyntaxException: java.lang.NumberFormatException: Expected a long but was 2.5 at line 1 column 2000 path $.max_ratio
00:21:22.339 [ERROR] qbittorrent.exporter.handler.QbtHttpHandler - An error occurred calling API
00:21:22.337 [INFO] qbittorrent.api.ApiClient - Response from /app/preferences endpoint was 200.
00:21:22.322 [INFO] qbittorrent.api.ApiClient - Response from /torrents/info endpoint was 200.
```

**Comment by caseyscarborough** [comment]
It appears that the `max_ratio` field is setup as a `long` so it doesn't accept decimal values. Thank you for reporting this, I will resolve this issue.

**Comment by caseyscarborough** [comment]
In the meantime, you can get around this by setting your Max Ratio to a whole number. You can check it in the Web UI under Settings > BitTorrent tab > Seeding Limits section > "When the ratio reaches".

Also, add the "Ratio Limit" column to your torrents list in the Web UI (by right clicking the columns at the top and selecting it) and check that none of them have a manual limit set to 2.5.
